<?php
require_once __DIR__ . '/../../includes/auth.php';
requireRole(getKnownRoles());
?>
<select id="geoSel">
  <option value=""> Please Select </option>
  <option value="Afghanistan">Afghanistan</option>
  <option value="Albania">Albania</option>
  <option value="Algeria">Algeria</option>
  <option value="Andorra">Andorra</option>
  <option value="Angola">Angola</option>
  <option value="Antigua and Barbuda">Antigua and Barbuda</option>
  <option value="Argentina">Argentina</option>
  <option value="Armenia">Armenia</option>
  <option value="Australia">Australia</option>
  <option value="Austria">Austria</option>
  <option value="Azerbaijan">Azerbaijan</option>
  <option value="Bahamas">Bahamas</option>
  <option value="Bahrain">Bahrain</option>
  <option value="Bangladesh">Bangladesh</option>
  <option value="Barbados">Barbados</option>
  <option value="Belarus">Belarus</option>
  <option value="Belgium">Belgium</option>
  <option value="Belize">Belize</option>
  <option value="Benin">Benin</option>
  <option value="Bhutan">Bhutan</option>
  <option value="Bolivia">Bolivia</option>
  <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
  <option value="Botswana">Botswana</option>
  <option value="Brazil">Brazil</option>
  <option value="Brunei">Brunei</option>
  <option value="Bulgaria">Bulgaria</option>
  <option value="Burkina Faso">Burkina Faso</option>
  <option value="Burundi">Burundi</option>
  <option value="Cabo Verde">Cabo Verde</option>
  <option value="Cambodia">Cambodia</option>
  <option value="Cameroon">Cameroon</option>
  <option value="Canada">Canada</option>
  <option value="Central African Republic">Central African Republic</option>
  <option value="Chad">Chad</option>
  <option value="Chile">Chile</option>
  <option value="China">China</option>
  <option value="Colombia">Colombia</option>
  <option value="Comoros">Comoros</option>
  <option value="Congo">Congo</option>
  <option value="Costa Rica">Costa Rica</option>
  <option value="Ivory Coast">Ivory Coast</option>
  <option value="Croatia">Croatia</option>
  <option value="Cuba">Cuba</option>
  <option value="Cyprus">Cyprus</option>
  <option value="Czech Republic">Czech Republic</option>
  <option value="Democratic Republic of the Congo">Democratic Republic of the Congo</option>
  <option value="Denmark">Denmark</option>
  <option value="Djibouti">Djibouti</option>
  <option value="Dominica">Dominica</option>
  <option value="Dominican Republic">Dominican Republic</option>
  <option value="Ecuador">Ecuador</option>
  <option value="Egypt">Egypt</option>
  <option value="El Salvador">El Salvador</option>
  <option value="Equatorial Guinea">Equatorial Guinea</option>
  <option value="Eritrea">Eritrea</option>
  <option value="Estonia">Estonia</option>
  <option value="Swaziland">Swaziland</option>
  <option value="Ethiopia">Ethiopia</option>
  <option value="Fiji">Fiji</option>
  <option value="Finland">Finland</option>
  <option value="France">France</option>
  <option value="Gabon">Gabon</option>
  <option value="Gambia">Gambia</option>
  <option value="Georgia">Georgia</option>
  <option value="Germany">Germany</option>
  <option value="Ghana">Ghana</option>
  <option value="Greece">Greece</option>
  <option value="Grenada">Grenada</option>
  <option value="Guatemala">Guatemala</option>
  <option value="Guinea">Guinea</option>
  <option value="Guinea-Bissau">Guinea-Bissau</option>
  <option value="Guyana">Guyana</option>
  <option value="Haiti">Haiti</option>
  <option value="Holy See">Holy See</option>
  <option value="Honduras">Honduras</option>
  <option value="Hungary">Hungary</option>
  <option value="Iceland">Iceland</option>
  <option value="India">India</option>
  <option value="Indonesia">Indonesia</option>
  <option value="Iran">Iran</option>
  <option value="Iraq">Iraq</option>
  <option value="Ireland">Ireland</option>
  <option value="Israel">Israel</option>
  <option value="Italy">Italy</option>
  <option value="Jamaica">Jamaica</option>
  <option value="Japan">Japan</option>
  <option value="Jordan">Jordan</option>
  <option value="Kazakhstan">Kazakhstan</option>
  <option value="Kenya">Kenya</option>
  <option value="Kiribati">Kiribati</option>
  <option value="Kuwait">Kuwait</option>
  <option value="Kyrgyzstan">Kyrgyzstan</option>
  <option value="Laos">Laos</option>
  <option value="Latvia">Latvia</option>
  <option value="Lebanon">Lebanon</option>
  <option value="Lesotho">Lesotho</option>
  <option value="Liberia">Liberia</option>
  <option value="Libya">Libya</option>
  <option value="Liechtenstein">Liechtenstein</option>
  <option value="Lithuania">Lithuania</option>
  <option value="Luxembourg">Luxembourg</option>
  <option value="Madagascar">Madagascar</option>
  <option value="Malawi">Malawi</option>
  <option value="Malaysia">Malaysia</option>
  <option value="Maldives">Maldives</option>
  <option value="Mali">Mali</option>
  <option value="Malta">Malta</option>
  <option value="Marshall Islands">Marshall Islands</option>
  <option value="Mauritania">Mauritania</option>
  <option value="Mauritius">Mauritius</option>
  <option value="Mexico">Mexico</option>
  <option value="Micronesia">Micronesia</option>
  <option value="Moldova">Moldova</option>
  <option value="Monaco">Monaco</option>
  <option value="Mongolia">Mongolia</option>
  <option value="Montenegro">Montenegro</option>
  <option value="Morocco">Morocco</option>
  <option value="Mozambique">Mozambique</option>
  <option value="Myanmar">Myanmar</option>
  <option value="Namibia">Namibia</option>
  <option value="Nauru">Nauru</option>
  <option value="Nepal">Nepal</option>
  <option value="Netherlands">Netherlands</option>
  <option value="New Zealand">New Zealand</option>
  <option value="Nicaragua">Nicaragua</option>
  <option value="Niger">Niger</option>
  <option value="Nigeria">Nigeria</option>
  <option value="North Korea">North Korea</option>
  <option value="North Macedonia">North Macedonia</option>
  <option value="Norway">Norway</option>
  <option value="Oman">Oman</option>
  <option value="Pakistan">Pakistan</option>
  <option value="Palau">Palau</option>
  <option value="Palestine State">Palestine State</option>
  <option value="Panama">Panama</option>
  <option value="Papua New Guinea">Papua New Guinea</option>
  <option value="Paraguay">Paraguay</option>
  <option value="Peru">Peru</option>
  <option value="Philippines">Philippines</option>
  <option value="Poland">Poland</option>
  <option value="Portugal">Portugal</option>
  <option value="Qatar">Qatar</option>
  <option value="Romania">Romania</option>
  <option value="Russia">Russia</option>
  <option value="Rwanda">Rwanda</option>
  <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
  <option value="Saint Lucia">Saint Lucia</option>
  <option value="Saint Vincent and the Grenadines">Saint Vincent and the Grenadines</option>
  <option value="Samoa">Samoa</option>
  <option value="San Marino">San Marino</option>
  <option value="Sao Tome and Principe">Sao Tome and Principe</option>
  <option value="Saudi Arabia">Saudi Arabia</option>
  <option value="Senegal">Senegal</option>
  <option value="Serbia">Serbia</option>
  <option value="Seychelles">Seychelles</option>
  <option value="Sierra Leone">Sierra Leone</option>
  <option value="Singapore">Singapore</option>
  <option value="Slovakia">Slovakia</option>
  <option value="Slovenia">Slovenia</option>
  <option value="Solomon Islands">Solomon Islands</option>
  <option value="Somalia">Somalia</option>
  <option value="South Africa">South Africa</option>
  <option value="South Korea">South Korea</option>
  <option value="South Sudan">South Sudan</option>
  <option value="Spain">Spain</option>
  <option value="Sri Lanka">Sri Lanka</option>
  <option value="Sudan">Sudan</option>
  <option value="Suriname">Suriname</option>
  <option value="Sweden">Sweden</option>
  <option value="Switzerland">Switzerland</option>
  <option value="Syria">Syria</option>
  <option value="Tajikistan">Tajikistan</option>
  <option value="Tanzania">Tanzania</option>
  <option value="Thailand">Thailand</option>
  <option value="Timor-Leste">Timor-Leste</option>
  <option value="Togo">Togo</option>
  <option value="Tonga">Tonga</option>
  <option value="Trinidad and Tobago">Trinidad and Tobago</option>
  <option value="Tunisia">Tunisia</option>
  <option value="Turkey">Turkey</option>
  <option value="Turkmenistan">Turkmenistan</option>
  <option value="Tuvalu">Tuvalu</option>
  <option value="Uganda">Uganda</option>
  <option value="Ukraine">Ukraine</option>
  <option value="United Arab Emirates">United Arab Emirates</option>
  <option value="United Kingdom">United Kingdom</option>
  <option value="United States of America">United States</option>
  <option value="Uruguay">Uruguay</option>
  <option value="Uzbekistan">Uzbekistan</option>
  <option value="Vanuatu">Vanuatu</option>
  <option value="Venezuela">Venezuela</option>
  <option value="Vietnam">Vietnam</option>
  <option value="Yemen">Yemen</option>
  <option value="Zambia">Zambia</option>
  <option value="Zimbabwe ">Zimbabwe </option>
  <option value="All Global">All - Global</option>
  <option value="EMEA">EMEA</option>
  <option value="APAC">APAC</option>
  <option value="LATAM">LATAM</option>
  <option value="North America">North America</option>
  <option value="South America">South America</option>
  <option value="Africa">Africa</option>
  <option value="ANZ">ANZ</option>
  <option value="Other">Other</option>
</select>

<select id="deptSel">
  <option value=""> Please Select </option>
  <option value="Information Technology">Information Technology</option>
  <option value="Sales">Sales</option>
  <option value="Marketing">Marketing</option>
  <option value="Finance">Finance</option>
  <option value="Human Resources">Human Resources</option>
  <option value="Operations">Operations</option>
  <option value="Engineering">Engineering</option>
  <option value="Product">Product</option>
  <option value="Customer Success">Customer Success</option>
  <option value="Legal">Legal</option>
  <option value="Research and Development">Research and Development</option>
  <option value="Administration">Administration</option>
  <option value="Other">Other</option>
</select>

<select id="levelSel">
  <option value="Owner">Owner</option>
  <option value="Partner">Partner</option>
  <option value="CXO">CXO</option>
  <option value="VP">VP</option>
  <option value="Head">Head</option>
  <option value="Director">Director</option>
  <option value="Manager">Manager</option>
  <option value="Senior">Senior</option>
  <option value="Entry">Entry</option>
  <option value="Intern">Intern</option>
  <option value="Other">Other</option>
</select>

<select id="empSel">
  <option value=""> Please Select </option>
  <option value="1-10">1-10</option>
  <option value="11-50">11-50</option>
  <option value="51-200">51-200</option>
  <option value="201-500">201-500</option>
  <option value="501-1000">501-1000</option>
  <option value="1001-5000">1001-5000</option>
  <option value="5001-10,000">5001-10000</option>
  <option value="10,001+">10001+</option>
  <option value="Any Employee Size">Any Employee Size</option>
  <option value="Other">Other</option>
</select>

<select id="indSel">
  <option value=""> Please Select </option>
  <option value="Education Management">Education Management</option>
  <option value="E-Learning">E-Learning</option>
  <option value="Higher Education">Higher Education</option>
  <option value="Primary/Secondary Education">Primary/Secondary Education</option>
  <option value="Research">Research</option>
  <option value="Building Materials">Building Materials</option>
  <option value="Civil Engineering">Civil Engineering</option>
  <option value="Construction">Construction</option>
  <option value="Architecture & Planning">Architecture & Planning</option>
  <option value="Design">Design</option>
  <option value="Graphic Design">Graphic Design</option>
  <option value="Accounting">Accounting</option>
  <option value="Business Supplies & Equipment">Business Supplies & Equipment</option>
  <option value="Environmental Services">Environmental Services</option>
  <option value="Events Services">Events Services</option>
  <option value="Executive Office">Executive Office</option>
  <option value="Facilities Services">Facilities Services</option>
  <option value="Human Resources">Human Resources</option>
  <option value="Information Services">Information Services</option>
  <option value="Management Consulting">Management Consulting</option>
  <option value="Outsourcing/Offshoring">Outsourcing/Offshoring</option>
  <option value="Professional Training & Coaching">Professional Training & Coaching</option>
  <option value="Security & Investigations">Security & Investigations</option>
  <option value="Staffing & Recruiting">Staffing & Recruiting</option>
  <option value="Retail">Retail</option>
  <option value="Supermarkets">Supermarkets</option>
  <option value="Wholesale">Wholesale</option>
  <option value="Mining & Metals">Mining & Metals</option>
  <option value="Oil & Energy">Oil & Energy</option>
  <option value="Utilities">Utilities</option>
  <option value="Automotive">Automotive</option>
  <option value="Aviation & Aerospace">Aviation & Aerospace</option>
  <option value="Chemicals">Chemicals</option>
  <option value="Defense & Space">Defense & Space</option>
  <option value="Electrical & Electronic Manufacturing">Electrical & Electronic Manufacturing</option>
  <option value="Food Production">Food Production</option>
  <option value="Glass, Ceramics & Concrete">Glass, Ceramics & Concrete</option>
  <option value="Industrial Automation">Industrial Automation</option>
  <option value="Machinery">Machinery</option>
  <option value="Mechanical or Industrial Engineering">Mechanical or Industrial Engineering</option>
  <option value="Packaging & Containers">Packaging & Containers</option>
  <option value="Paper & Forest Products">Paper & Forest Products</option>
  <option value="Plastics">Plastics</option>
  <option value="Railroad Manufacture">Railroad Manufacture</option>
  <option value="Renewables & Environment">Renewables & Environment</option>
  <option value="Shipbuilding">Shipbuilding</option>
  <option value="Textiles">Textiles</option>
  <option value="Banking">Banking</option>
  <option value="Capital Markets">Capital Markets</option>
  <option value="Financial Services">Financial Services</option>
  <option value="Insurance">Insurance</option>
  <option value="Investment Banking">Investment Banking</option>
  <option value="Investment Management">Investment Management</option>
  <option value="Venture Capital & Private Equity">Venture Capital & Private Equity</option>
  <option value="Airlines/Aviation">Airlines/Aviation</option>
  <option value="Gambling & Casinos">Gambling & Casinos</option>
  <option value="Hospitality">Hospitality</option>
  <option value="Leisure, Travel & Tourism">Leisure, Travel & Tourism</option>
  <option value="Restaurants">Restaurants</option>
  <option value="Recreational Facilities & Services">Recreational Facilities & Services</option>
  <option value="Sports">Sports</option>
  <option value="Arts & Crafts">Arts & Crafts</option>
  <option value="Fine Art">Fine Art</option>
  <option value="Performing Arts">Performing Arts</option>
  <option value="Photography">Photography</option>
  <option value="Biotechnology">Biotechnology</option>
  <option value="Hospital & Health Care">Hospital & Health Care</option>
  <option value="Medical Device">Medical Device</option>
  <option value="Medical Practice">Medical Practice</option>
  <option value="Mental Health Care">Mental Health Care</option>
  <option value="Pharmaceuticals">Pharmaceuticals</option>
  <option value="Veterinary">Veterinary</option>
  <option value="Computer Hardware">Computer Hardware</option>
  <option value="Computer Networking">Computer Networking</option>
  <option value="Nanotechnology">Nanotechnology</option>
  <option value="Semiconductors">Semiconductors</option>
  <option value="Telecommunications">Telecommunications</option>
  <option value="Wireless">Wireless</option>
  <option value="Commercial Real Estate">Commercial Real Estate</option>
  <option value="Real Estate">Real Estate</option>
  <option value="Alternative Dispute Resolution">Alternative Dispute Resolution</option>
  <option value="Law Practice">Law Practice</option>
  <option value="Legal Services">Legal Services</option>
  <option value="Apparel & Fashion">Apparel & Fashion</option>
  <option value="Consumer Electronics">Consumer Electronics</option>
  <option value="Consumer Goods">Consumer Goods</option>
  <option value="Consumer Services">Consumer Services</option>
  <option value="Cosmetics">Cosmetics</option>
  <option value="Food & Beverages">Food & Beverages</option>
  <option value="Furniture">Furniture</option>
  <option value="Luxury Goods & Jewelry">Luxury Goods & Jewelry</option>
  <option value="Sporting Goods">Sporting Goods</option>
  <option value="Tobacco">Tobacco</option>
  <option value="Wine and Spirits">Wine and Spirits</option>
  <option value="Agriculture">Agriculture</option>
  <option value="Dairy">Dairy</option>
  <option value="Farming">Farming</option>
  <option value="Fishery">Fishery</option>
  <option value="Ranching">Ranching</option>
  <option value="Market Research">Market Research</option>
  <option value="Marketing & Advertising">Marketing & Advertising</option>
  <option value="Newspapers">Newspapers</option>
  <option value="Online Media">Online Media</option>
  <option value="Printing">Printing</option>
  <option value="Public Relations & Communications">Public Relations & Communications</option>
  <option value="Publishing">Publishing</option>
  <option value="Translation & Localization">Translation & Localization</option>
  <option value="Writing & Editing">Writing & Editing</option>
  <option value="Nonprofit">Nonprofit</option>
  <option value="Civic & Social Organization">Civic & Social Organization</option>
  <option value="Fundraising">Fundraising</option>
  <option value="Individual & Family Services">Individual & Family Services</option>
  <option value="International Trade & Development">International Trade & Development</option>
  <option value="Libraries">Libraries</option>
  <option value="Museums & Institutions">Museums & Institutions</option>
  <option value="Non-Profit Organization">Non-Profit Organization</option>
  <option value="Philanthropy">Philanthropy</option>
  <option value="Program Development">Program Development</option>
  <option value="Religious Institutions">Religious Institutions</option>
  <option value="Think Tanks">Think Tanks</option>
  <option value="Computer & Network Security">Computer & Network Security</option>
  <option value="Computer Software">Computer Software</option>
  <option value="Information Technology & Services">Information Technology & Services</option>
  <option value="Internet">Internet</option>
  <option value="Import & Export">Import & Export</option>
  <option value="Logistics & Supply Chain">Logistics & Supply Chain</option>
  <option value="Maritime">Maritime</option>
  <option value="Package/Freight Delivery">Package/Freight Delivery</option>
  <option value="Transportation/Trucking/Railroad">Transportation/Trucking/Railroad</option>
  <option value="Warehousing">Warehousing</option>
  <option value="Animation">Animation</option>
  <option value="Broadcast Media">Broadcast Media</option>
  <option value="Computer Games">Computer Games</option>
  <option value="Entertainment">Entertainment</option>
  <option value="Media Production">Media Production</option>
  <option value="Mobile Games">Mobile Games</option>
  <option value="Motion Pictures & Film">Motion Pictures & Film</option>
  <option value="Music">Music</option>
  <option value="Alternative Medicine">Alternative Medicine</option>
  <option value="Health, Wellness & Fitness">Health, Wellness & Fitness</option>
  <option value="Law Enforcement">Law Enforcement</option>
  <option value="Military">Military</option>
  <option value="Public Safety">Public Safety</option>
  <option value="Government Administration">Government Administration</option>
  <option value="Government Relations">Government Relations</option>
  <option value="International Affairs">International Affairs</option>
  <option value="Judiciary">Judiciary</option>
  <option value="Legislative Office">Legislative Office</option>
  <option value="Political Organization">Political Organization</option>
  <option value="Public Policy">Public Policy</option>
  <option value="Any Industry">Any Industry</option>
  <option value="Other">Other</option>
</select>

<select id="revSel">
  <option value=""> Please Select </option>
  <option value="$1M-$10M">$1M-$10M</option>
  <option value="$10M-$50M">$10M-$50M</option>
  <option value="$50M-$100M">$50M-$100M</option>
  <option value="$100M-$500M">$100M-$500M</option>
  <option value="$500M-$1B">$500M-$1B</option>
  <option value="$1B-$10B">$1B-$10B</option>
  <option value="$10B+">$10B+</option>
  <option value="Any Revenue Size">Any Revenue Size</option>
  <option value="Other">Other</option>
</select>
